version: '3.8'

services:
  db:
    volumes:
      # Store data on PC via network mount
      - //192.168.0.24/SharedData/postgres:/var/lib/postgresql/data
      
  storage:
    volumes:
      - //192.168.0.24/SharedData/storage:/var/lib/storage
      
  # Add any other services that need shared storage